# Generated by Django 4.0.3 on 2022-06-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistrations',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverregistrations',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='driverregistrations',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='driverregistrations',
            name='mobile',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
